# FROM prefecthq/prefect:2.10.17-python3.11
FROM python:3.11

RUN pip install --no-cache-dir prefect==2.11.4 s3fs==2022.8.2 psycopg2==2.9.7
# RUN apt update && \
#     pip install psycopg2-binary==2.9.3 s3fs==2022.8.2